name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  # ======================
  # 1️⃣ CI JOB – BUILD
  # ======================
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=sunnyypatel/docker-cicd:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          docker tag $IMAGE_TAG sunnyypatel/docker-cicd:latest
          docker push sunnyypatel/docker-cicd:latest

  # ======================
  # 2️⃣ CD JOB – DEPLOY
  # ======================
  deploy:
    name: Deploy to Mac Server
    runs-on: self-hosted
    needs: build # deploy will only run after build completes

    steps:
      - name: Deploy Docker container
        run: |
          IMAGE_TAG=sunnyypatel/docker-cicd:${{ github.sha }}
          cd ~/next-app
          ./deploy.sh $IMAGE_TAG
